# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-10 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=40)),
                ('Day', models.CharField(max_length=40)),
                ('Morning', models.CharField(max_length=50)),
                ('Evening', models.CharField(max_length=60)),
                ('General', models.CharField(max_length=70)),
            ],
        ),
    ]
