# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-27 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
                ('Day', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=56, null=True)),
                ('Morning', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Akshay', 'Akshay'), ('Ankit', 'Ankit'), ('Dikshant', 'Dikshant'), ('Nitish', 'Nitish'), ('Priyanka', 'Priyanka')], max_length=37, null=True)),
                ('Evening', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Akshay', 'Akshay'), ('Ankit', 'Ankit'), ('Dikshant', 'Dikshant'), ('Nitish', 'Nitish'), ('Priyanka', 'Priyanka')], max_length=37, null=True)),
                ('General', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Akshay', 'Akshay'), ('Ankit', 'Ankit'), ('Dikshant', 'Dikshant'), ('Nitish', 'Nitish'), ('Priyanka', 'Priyanka')], max_length=37, null=True)),
                ('Planned', models.TextField(blank=True, max_length=50, null=True)),
                ('Comp_off', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Akshay', 'Akshay'), ('Ankit', 'Ankit'), ('Dikshant', 'Dikshant'), ('Nitish', 'Nitish'), ('Priyanka', 'Priyanka')], max_length=37, null=True)),
                ('Leave', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Akshay', 'Akshay'), ('Ankit', 'Ankit'), ('Dikshant', 'Dikshant'), ('Nitish', 'Nitish'), ('Priyanka', 'Priyanka')], max_length=37, null=True)),
            ],
        ),
    ]
