# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-02 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='date',
            field=models.CharField(max_length=40),
        ),
    ]
